name: Lint

on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  black:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit, 'ci skip') || !contains(github.event.head_commit, 'from socialgene/release-please') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable
